version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: be-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - workplace
    networks:
      - app-network

  workplace:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: workplace
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PASSWORD=tvnaapp
      # - CACHE_DRIVER=redis
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
      - pgadmin
      - supervisor
    networks:
      - app-network
    links:
      - db
      - redis
      - pgadmin

  db:
    image: postgres
    container_name: db
    restart: always
#    env_file:
#      - .env
#    command: --default-authentication-plugin=mysql_native_password
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: tvnaapp
        POSTGRES_DB: people_management
        PGDATA: /var/lib/postgres/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./docker-compose/postgres:/var/lib/postgres
    networks:
      - app-network
  mongo:
      image: mongo
      container_name: mongo
      restart: always
      ports:
          - 27017:27017
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
          image: mongo-express
          restart: always
          ports:
              - 8081:8081
          environment:
              ME_CONFIG_MONGODB_ADMINUSERNAME: root
              ME_CONFIG_MONGODB_ADMINPASSWORD: example
              ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: my-pgadmin
      ports:
          - 82:80
      environment:
          PGADMIN_DEFAULT_EMAIL: root@admin.com
          PGADMIN_DEFAULT_PASSWORD: 12345678
      networks:
          - app-network
      depends_on:
          - db
      volumes:
          - ./docker-compose/pgadmin/data:/var/lib/pgadmin/data
  redis:
    image: redis:latest
    container_name: be-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass tvnaapp
#    environment:
#      REDIS_PASSWORD: tvnaapp
    ports:
      - 6379:6379
    networks:
      - app-network
  supervisor:
    build:
        context: ./
        dockerfile: ./supervisor/Dockerfile
    container_name: supervisor
    ports:
        - 22
        - 80
    volumes:
        - ./:/var/www/html
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
