version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: be-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network
    
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: be-app
    container_name: be-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    links:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
